List<String> suggestionsKor = [
  '수강신청 가능 학점은 몇 학점인가요',
  '수강신청 학점 이월이 가능한가요',
  '수강신청은 언제/어떻게 하나요',
  '수강한 과목의 이수 구분을 변경하고 싶어요',
  '신입생 수강신청은 언제/어떻게 하나요',
  '계절학기 수강신청은 언제/어떻게 하나요',
  '봉사활동을 학점으로 인정받을 수 있나요',
  '이수 학점을 확인하고 싶어요',
  '편입생 학점 인정을 안내해 주세요',
  '학점교류에 대해 알고 싶어요',
  '교환학생 학점 인정에 대해 알려주세요',
  '군 복무 중 학점 취득할 수 있나요',
  '대학 및 학과(부)별 졸업이수학점 알려주세요',
  '학년별 수료학점 기준이 궁금해요',
  '대학 규정 및 학칙에 대해 알려주세요',
  '대학본부에 대해 알려주세요',
  '우리학교 도서관이 궁금해요',
  '도서(책) 대출 기간을 연장할 수 있나요',
  '도서관 운영시간과 휴관일이 궁금해요',
  '증명서는 어떻게 발급하나요',
  '강의계획서를 확인하고 싶어요',
  '강의평가는 언제 어떻게 진행되나요',
  '무당이 시간표와 노선을 알고 싶어요',
  '교내 행정부서의 근무시간을 알려주세요',
  '다전공 합격 여부는 언제/어떻게 확인할 수 있나요',
  '등록금 금액(등록금 고지서) 확인하고 싶어요',
  '등록금 납부 방법에 대해서 알려주세요',
  '등록금 납부 확인 어떻게 하나요',
  '등록금은 어떤 경우에 환불(반환)되나요',
  '신입생 장학금은 어떤게 있나요',
  '신청 가능한 장학금이 있나요',
  '장학금 정보가 궁금해요',
  '재학생 장학금은 어떤게 있나요',
  '해외교류프로그램 장학금에 대해 알고시펑요',
  '내 장학 금액이 궁금해',
  '복학하려면 어떻게 해야하나요',
  '군입대 휴학 및 복학은 어떻게 신청하나요',
  '졸업 가능 여부를 확인하고 싶어요',
  '졸업 요건을 충족하지 못했을 때는 어떻게 되나요',
  '졸업생 도서관 출입증 발급 방법이 궁금해요',
  '졸업을 유예할 수 있는 방법이 있나요',
  '입학/졸업 일자를 확인하고 싶어요',
  '졸업하기 위해 필요한 요건이 어떻게 되나요',
  '캠퍼스맵(건물 위치) 보여주세요',
  '학교 건물 도면 요청방법 알려주세요',
  '교환학생 및 방문학생에 대해 알려주세요',
  '외부인(일반인)이 우리 학교 도서관을 이용할 수 있나요',
  '학교 마스코트가 뭔가요',
  '학교 모바일 앱을 알고 싶어요',
  '학교의 이념 및 역사를 알고 싶어요',
  '우리학교 취업률이 궁금해요',
  '학교 배상 책임보험에 대해 알려주세요',
  '가천대학교 동창회가 있나요',
  '가천대 상징을 알고 싶어요',
  '가천대(글로벌) 가는 법을 알려주세요',
  '가천대에 대해 알려주세요',
  '무인증명발급기 어떻게 사용하나요',
  '오피스365(office)를 사용하고 싶어요',
  '와이파이 사용방법이 궁금해요',
  '유선 네트워크(ip배정)를 사용하고 싶어요',
  '아르테크네, 라곰, 메타버스 사용하고 싶어요',
  '포탈 사용방법이 궁금해요',
  '다전공(복수/연계/융합/부전공) 신청할래요',
  '근로 신청하고 싶어요',
  '도메인 신청 방법이 궁금해요',
  '학과 사물함 신청어떻게 해',
  '도서관 사물함 신청 어떻게 해',
  '학생증 신청방법 알려주세요',
  '도서관 장애인 자료배달 서비스가 있나요',
  '도서관에 자료(도서/책)를 기증하고 싶어요',
  '분실물 정보'
      '생활관에 대한 정보는 어디서 보나요',
  '아르바이트 정보',
  '외부교육 정보를 알려주세요',
  '개인정보 수정하는 방법 알려줘',
  '0원 등록은 언제/어떻게 하나요',
  '글로벌 캠퍼스 학식 메뉴 확인할래요',
  '포탈 사진 변경 어떻게 하나요',
  '학생증/신분증 사진 변경 어떻게 하나요',
  '운동장 대여할 수 있나요',
  '체육관 대여할 수 있나요',
  '공연장 대여할 수 있나요',
  '학위수여식 관련 사항(학위복 대여/졸업앨범 수령 등) 알려주세요',
  '기숙사 고장 수리 신청 방법은 어떻게 되나요',
  '기숙사 공지사항 알려주세요',
  '기숙사 내 비상시 행동요령에 대해 알려주세요',
  '기숙사 무선네트워크 사용법을 알려주세요',
  '기숙사 생활규정에 대해 알려주세요',
  '기숙사 생활에 대한 정보를 알려주세요',
  '기숙사 생활점검 및 지도는 어떻게 하나요',
  '기숙사 시설에 대해 알려주세요',
  '기숙사 외부인 방문 규정은 어떻게 되나요',
  '기숙사 우편물 수령에 대해 알려주세요',
  '기숙사 입퇴사에 대한 정보를 얻고 싶어요',
  '기숙사 지각/무단외박에 대한 규정은 어떻게 되나요',
  '기숙사 출입 개방 시간은 어떻게 되나요',
  '동창정보 등록하고 싶어요',
  '등록금 고지서 출력하고 싶어요',
  '등록금 납부 시 이체한도가 모자랍니다',
  '등록금 납부 시 입금자명이 달라도 되나요',
  '등록금 납부확인서는 언제 발급되나요',
  '등록금 분할납부 가능한가요',
  '도서관 그룹활동실을 예약하고 싶어요',
  '도서관 동영상 강좌를 이용하고 싶어요',
  '도서관 서비스별 연락처 알려주세요',
  '도서관 장애인 서비스를 알려주세요',
  '휴학생/졸업생의 도서관 이용방법을 알려주세요',
  '도서관 이용정보를 알고 싶어요',
  '도서관 자료실이나 열람실을 안내해주세요',
  '도서관 출력/복사 시설에 대해 알려주세요',
  '가천대 뉴스 알려주세요',
  '가천대 비전에 대해 알고 싶어요',
  '가천대 사진 찾아주세요',
  '가천대 역사에 대해 알려주세요',
  '가천대 vr투어 보여주세요',
  '가천대 홍보자료 보고싶어요',
  '무당이 이용에 대해 안내해주세요',
  '무당이 정류장은 어디인가요',
  '무당이 탑승시 신분증(학생증/교직원증)이 필요한가요',
  '복수전공 이수자의 학점중복인정에 대해 알려주세요',
  '부,복수전공 승인 이전에 수강한 해당 전공의 교과목도 부,복수전공 학점으로 인정받을 수 있나요',
  '부,복수전공 학점 중복인정 시 총 이수학점에는 어떻게 반영되나요',
  '수강신청 후 철회기간에 철회한 학점도 이월 가능한가요',
  '초과학기 등록생도 학점이월이 가능한가요',
  '편입생 전적대학 학점인정에 대해 알려주세요',
  '학점 이월 시 몇 학점까지 이월 가능한가요',
  '학점 교류 교과목 수강신청하고 싶어요',
  '마지막 8학기 정규 수강을 하고 졸업학점이 남아 계절학기를 들으려고 합니다.',
  '졸업(예정)석차는 어디서 볼 수 있나요',
  '졸업/수강 시뮬레이션',
  '졸업 관련 자주 묻는 질문 알려주세요',
  '졸업 신청하고 싶어요',
  '졸업 요건 알려주세요',
  '졸업식 일정에 대해 알려주세요',
  '졸업예정증명서는 언제부터 발급 가능하나요',
  '외국인 유학생 휴학/자퇴 절차 알려주세요',
  '초과학기 등록생도 휴학이 가능한가요',
  '휴학 가능 기간 알려주세요',
  '휴학 문의 연락처 알려주세요',
  '휴학 시 등록금 반환에 대해 알려주세요',
  '휴학 시 유의사항에 대해 알려주세요',
  '휴학 접수 불가 해결방법 알려주세요',
  '복수전공을 a전공에서 b전공으로 바꾸고 싶습니다. 어떻게 변경하나요',
  '수강신청 변경했는데 사이버캠퍼스에 반영되지 않아요',
  '이미 등록금 납부를 하였는데 납부 방법 변경이 가능한가요',
  '이수 중인 복수전공을 부전공으로 바꾸고 싶습니다. 별도의 변경 절차가 있나요',
  '장학금 지급 계좌 변경하고 싶어요',
  '취업 자료 얻고 싶어요',
  '취업지원 정보 얻고 싶어요',
  'f학점을 받고 재수강을 하면 성적증명서에 이전에 f를 받은 것이 표기가 되나요',
  '재수강 신청하고 싶어요',
  '(필수) 교양 교과목 이수 기준에 대해 알려주세요',
  '졸업하려면 이수해야 하는 교양 강의 알려주세요',
  '복수전공 신청 제한 전공(학과)에 대해 알려주세요',
  '부전공 신청 제한 전공(학과)에 대해 알려주세요',
  '부전공도 전공기초나 전공필수과목을 꼭 이수해야 하나요',
  '전공 결정이 뭐에요?',
  '전공 변경 신청하고 싶어요',
  '부,복수전공 신청은 재학 중 한 번만 가능한가요',
  '자퇴 시에 등록금 반환에 대해 알려주세요',
  '자퇴하고 싶어요',
  '복학 신청을 못했습니다. 수강신청을 할 수 있나요',
  '휴학을 신청한 기간이 종료되었습니다. 복학신청을 꼭 해야하나요',
  '조기복학 신청을 했습니다. 수강신청을 언제 할 수 있나요',
  '계절학기 등록금 납부하고 싶어요',
  '계절학기 취소 시 등록금 반환에 대해 알려주세요',
  '본교생인데 사이버캠퍼스 로그인이 안돼요',
  '사이버캠퍼스 공지사항 확인하고 싶어요',
  '사이버캠퍼스 관련 자주 묻는 질문 알려주세요',
  '사이버캠퍼스 매뉴얼 알려주세요',
  '사이버캠퍼스 메시지 확인하고 싶어요',
  '사이버캠퍼스 자료 확인하고 싶어요',
  '사이버캠퍼스 프로필 사진은 어떻게 등록하나요',
  '사이버캠퍼스에 q&a를 작성하고 싶어요',
  '사이버캠퍼스에 대해 알려주세요',
  '총장님이 궁금해요',
  '교육이념이 궁금해요',
  '학교 역사가 궁금해요',
  '상징이 궁금해요',
  '마스코트가 궁금해요',
  '교가가 궁금해요',
  '규정집이 궁금해요',
  '통계연보가 궁금해요.',
  '정보공개청구를 하고싶어요',
  '자매결연대학이 궁금해요',
  '조직도가 궁금해요',
  '글로벌캠퍼스 가는 법 궁금해요',
  '메디컬캠퍼스 가는 법 궁금해요',
  '셔틀버스 궁금해요',
  '통학버스 궁금해요',
  'VR투어',
  '글로벌캠퍼스가 궁금해요',
  '메디컬캠퍼스가 궁금해요',
  '가천리버럴아츠컬리지가 궁금해요',
  '경영대학이 궁금해요',
  '사회과학대학이 궁금해요',
  '인문대학이 궁금해요',
  '법과대학이 궁금해요',
  '공과대학이 궁금해요',
  '바이오나노대학이 궁금해요',
  'IT융합대학이 궁금해요',
  '한의과대학이 궁금해요',
  '예술･체육 대학이 궁금해요',
  '미래산업대학이 궁금해요',
  '창업대학이 궁금해요',
  '의과대학이 궁금해요',
  '약학대학이 궁금해요',
  '간호대학이 궁금해요',
  '보건과학대학이 궁금해요',
  '가천리버럴아츠컬리지가 궁금해요',
  '하와이가천글로벌센터가 궁금해요',
  '강화캠퍼스가 궁금해요',
  '평생교육원이 궁금해요',
  '공지사항이 궁금해요',
  '코로나19가 공지사항이 궁금해요',
  '학사공지가 궁금해요',
  '장학공지가 궁금해요',
  '학생소식이 궁금해요',
  '취업공지가 궁금해요',
  '비교과 공지가 궁금해요',
  '기타공지가 궁금해요',
  '원격교육지원이 궁금해요',
  '교육성화관리센터가 궁금해요',
  'ESG센터가 궁금해요',
  'ArTechne센터가 궁금해요',
  '의사소통센터가 궁금해요',
  '비교과Wind시스템이 궁금해요',
  '대학일자리플러스센터가 궁금해요',
  '현장실습지원센터가 궁금해요',
  '가천인권센터가 궁금해요',
  '학생상담센터가 궁금해요',
  '상담/심리검사신청이 궁금해요',
  '학생증발급이 궁금해요',
  '모바일 학생증 궁금해요',
  '학생증 체크카드 궁금해요',
  '정기주차 궁금해요',
  '메디컬캠퍼스 정기주차 궁금해요',
  '분실물센터 궁금해요',
  '총학생회가 궁금해요',
  '중앙동아리가 궁금해요',
  '글로벌 중앙동아리가 궁금해요',
  '메디컬캠퍼스 중앙동아리가 궁금해요',
  '학생군사교육단(ROTC)이 궁금해요',
  '학생생활가이드북이 궁금해요'
];

List<String> suggestionsEng = [
  "How many credits can you apply for the course?",
  "Is it possible to carry over the credits for the course?",
  "When/How do I apply for the class?",
  "I want to change the classification of the subjects I took",
  "When/How can I register for a new student's course?",
  "When/how do I sign up for the seasonal semester?",
  "Can volunteer work be recognized as a credit?",
  "I want to check my GPA",
  "Please let me know how to get credit for a transfer student",
  "I want to know about credit exchange",
  "Please tell me about the credit recognition for exchange students",
  "Can I get credits while serving in the military?",
  "Please tell me the number of graduation credits for each university and department",
  " curious about the standard of credits for each grade",
  "Tell me about the university regulations and school regulations,",
  "Tell me about the university headquarters",
  " curious about my school library",
  "Can I extend the loan period for books?",
  " curious about the library's operating hours and closing days",
  "How do you issue a certificate?",
  "I want to check the syllabus",
  "When and how will the lecture evaluation be conducted?",
  "I'd like to know the timetable and route of Mudang",
  "Tell me how many hours you work in the school administration department,",
  "When/how can I check if I've passed multiple majors?",
  "I want to check the tuition amount (tuition bill),",
  "Please tell me how to pay tuition fees",
  "How do I check the tuition payment?",
  "In what cases will the tuition be refunded?",
  "What kind of scholarship do you have for freshmen?",
  "Is there a scholarship I can apply for",
  " curious about the scholarship information",
  "What kind of scholarships do you have for students?",
  "Please know about scholarships for overseas exchange programs",
  " curious about my scholarship",
  "What should I do to return to school?",
  "How can I apply for a leave of absence from military service and return to school?",
  "I want to see if I can graduate",
  "What happens if you don't meet the graduation requirements?",
  "I want to know how to get a diploma library pass",
  "Is there a way to put off graduation?",
  "I want to check the date of admission/graduation",
  "What are the requirements to graduate?",
  "Show us the campus map",
  "Please tell me how to request drawings for school buildings",
  "Please tell me about exchange students and visiting students",
  "Can outsiders use our school library?",
  "What's the school mascot?",
  "I want to know the mobile app for my school",
  "I want to know the ideology and history of the school",
  " curious about the employment rate at my school",
  "Tell me about school liability insurance",
  "Is there a reunion at Gachon University?",
  "I want to know the symbol of Gachon",
  "Please tell me how to get to Gachon University (Global),",
  "Tell me about Gachon University",
  "How do you use an unauthorized certificate issuing machine?",
  "I want to use Office 365",
  "I want to know how to use Wi-Fi",
  "I want to use a wired network,",
  "I want to use ARTECH, Lagom, and the metaverse",
  "I want to know how to use the portal",
  "I want to apply for multiple majors (multiple/connection/convergence/non-major),",
  "I want to apply for work",
  "I want to know how to apply for the domain",
  "How do I apply for a major locker?",
  "How can I apply for a library locker?",
  "Tell me how to apply for your student ID",
  "Is there a delivery service for disabled people in the library?",
  "I want to donate materials (books/books) to the library",
  "Information about lost objects.",
  "Where can I find information about my living room?",
  'Part-time job information',
  "Tell me the external training information",
  "Tell me how to change my personal information",
  "When/How can I register for zero won?",
  "I want to check out the global campus food menu",
  "How can I change my photo?",
  "How can I change my student ID/ID photo?",
  "Can I rent a playground?",
  "Can I rent a gym?",
  "Can I rent a concert hall?",
  "Please let me know about the graduation ceremony (rental of the graduation clothes, etc.)",
  "How can I apply for a breakdown repair at the dorm?",
  "Please tell us the announcement about the dorm",
  "Please tell me how to act in case of emergency in the dorm",
  "Please tell me how to use the wireless network at the dorm",
  "Tell me about the living rules of the dorm",
  "Please tell me information about your dorm life",
  "How do you check and guide your living in the dorm?",
  "Tell me about the dorm facilities",
  "What are the rules for visiting outsiders at the dorm?",
  "Tell me about receiving mail from the dorm",
  "I want to get information about my retirement from the dorm",
  "What are the rules for late-night stay at the dorm?",
  "What's the opening time for the dorm?",
  "I want to register Dongchang information",
  "I want to print out my tuition bill,",
  "The transfer limit is insufficient when paying tuition,",
  "Can I change the name of the depositor when I pay the tuition?",
  "When will the tuition payment confirmation be issued?",
  "Can I pay the tuition fee in installments?",
  "I want to reserve a group activity room in the library",
  "I want to use the library video course",
  "Please tell me the contact information for each library service",
  "Please tell me the service for the disabled in the library",
  "Please tell me how to use the library for students taking a leave of absence.",
  "I want to know the library usage information",
  "Please guide me to library archives or reading rooms",
  "Tell me about the library output/copy facilities",
  "Please tell us the news about Gachon University",
  "I want to know about the vision of Gachon University",
  "Please find a photo of Gachon University",
  "Tell us about the history of Gachon University",
  "Please show us your vr tour at Gachon University",
  "I want to see the promotional materials for Gachon University",
  "Please let me know about the use of Mudang",
  "Where is the Mudangi stop?",
  "Do I need an ID card (student card/teacher card) when I get on board?",
  "Please tell me about double credit recognition for those who have completed a double major",
  "Can the subjects of the relevant major taken before the approval of the department or double major be recognized as credits for the department or double major?",
  "How is it reflected in the total number of credits that are completed when multiple credits are recognized?",
  "Can I carry over the credits withdrawn during the withdrawal period after applying for the course?",
  "Is it possible for students who are enrolled in the excessive semester to pass grades?",
  "Please tell me about the college credit recognition",
  "How many credits can I carry over if I carry over my credit?",
  "I'd like to sign up for a credit exchange course,",
  " going to take a regular course for the last eight semesters, and I have graduation credits left, so  going to take the seasonal semester",
  "Where can I see the graduation tickets?",
  'Graduation/College Course Simulation',
  "Please tell me questions about graduation",
  "I want to apply for graduation",
  "Please tell me your graduation requirements",
  "Tell me about your graduation schedule",
  "When can I get a certificate of graduation?",
  "Please tell me how to take a leave of absence or drop out of school for international students",
  "Is it possible to take a leave of absence for students who are enrolled in the semester?",
  "Tell me how long you can take a leave of absence",
  "Please tell me the contact information for taking a leave of absence",
  "Tell me about returning tuition fees when you take a leave of absence",
  "Please let me know what to do when taking a leave of absence",
  "Please tell me how to take a leave of absence",
  "I want to change my double major from a major to b major. How can I change it?",
  "I changed my application, but it's not reflected in the cyber campus,",
  "I've already paid the tuition fee, can I change the payment method?",
  "I want to change my double major to a minor. Is there a separate change process?",
  "I want to change my scholarship account,",
  "I want to get employment data",
  "I want to get job support information",
  "If you get an f credit and retake the class again, does your transcript indicate that you got an f before?",
  "I want to apply for a retake",
  "(Required) Please tell me the standard for completing liberal arts courses",
  "Please tell me a liberal arts course that I need to complete to graduate",
  "Tell me about the major(department) that is restricted from applying for a double major",
  "Please tell me about the major(department) that is restricted from applying for the minor engineering",
  "Do I have to complete a basic major or a required major in a minor engineering course?",
  "What's your major decision?",
  "I want to change my major",
  "Can I apply for a double major only once while  in school?",
  "Please let me know about the return of tuition fees when you drop out",
  "I want to drop out",
  "I couldn't register to return to school. Can I register for a course?",
  "The period of my leave of absence has ended. Do I have to go back to school?",
  "I applied to return to school early. When can I register for classes?",
  "I want to pay for the seasonal semester",
  "Please let me know about the return of tuition fees when canceling the seasonal semester,",
  " a student, but I can't log in to Cyber Campus",
  "I want to check the announcement on Cyber Campus",
  "Please tell us questions about Cyber Campus",
  "Please tell us the Cyber Campus manual",
  "I want to check the messages on Cyber Campus",
  "I want to check the Cyber Campus data",
  "How do you register your profile picture on the cyber campus?",
  "I want to write a q&a on the cyber campus",
  "Tell me about Cyber Campus",
  " curious about the president",
  " curious about your educational philosophy",
  " curious about your school history",
  " curious about the symbol",
  " curious about your mascots",
  " curious about your school",
  " curious about the rule book",
  " curious about the statistical yearbook.",
  "I want to request information disclosure",
  " curious about your sisterhood college",
  " curious about the organization chart",
  "I want to know how to go to the Global Campus",
  "I want to know how to go to the medical campus",
  " curious about the shuttle bus",
  " curious about the school bus",
  "VR Tour",
  " curious about the Global Campus",
  " curious about the medical campus",
  " curious about Gachon Liberal Arts College",
  " curious about the business school",
  " curious about the College of Social Sciences",
  " curious about humanities college",
  " curious about law school",
  " curious about engineering college",
  " curious about Bionano University",
  " curious about IT convergence college",
  " curious about oriental medicine college",
  " curious about the college of arts and sports",
  " curious about Future Industrial College",
  " curious about the start-up college",
  " curious about medical school",
  " curious about the pharmacy college",
  " curious about nursing college",
  " curious about the College of Health Sciences",
  " curious about Gachon Liberal Arts College",
  " curious about Hawaii Gachon Global Center",
  " curious about Ganghwa Campus",
  " curious about the lifelong education center",
  " curious about the announcement",
  " curious about the COVID-19 announcement",
  " curious about the announcement of the academy",
  " curious about the scholarship announcement",
  " curious about your news",
  " curious about your job announcement",
  " curious about the non-curricular announcement",
  " curious about the announcement of the guitar",
  " curious about remote education support",
  " curious about the Education Seonghwa Management Center",
  " curious about the ESG center",
  " curious about the ArTechne center",
  " curious about the communication center",
  " curious about the non-curricular Wind system",
  " curious about the University Job Plus Center",
  " curious about the field training support center",
  " curious about the Gachon Human Rights Center",
  " curious about the student counseling center",
  " curious about your application for counseling/psychological examination",
  " curious about your student ID",
  " curious about your mobile student ID",
  " curious about your student ID card",
  " curious about regular parking",
  " curious about regular parking at the medical campus",
  " curious about the lost and found center",
  " curious about the student council",
  " curious about the central club",
  " curious about the global central club",
  " curious about the center of the medical campus",
  " curious about the ROTC",
  " curious about your student life guidebook."
];
